[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vivideo"
version = "0.0.1"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]

[tool.black]
line-length = 119